name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        shard: [1, 2, 3, 4, 5]  # Define the number of parallel shards you want to run

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Specify the Node.js version (adjust as needed)

      - name: Install dependencies
        run: npm install  # Install dependencies using npm ci for a clean install

      - name: Set environment variable for shard
        run: echo "SHARD=${{ matrix.shard }}" >> $GITHUB_ENV  # Export shard as environment variable

      - name: Run Cypress Tests in Parallel
        run: |
          npx cypress run --record --key cc7e1148-9689-4fe6-97a0-035a8a50ed95 --parallel --ci-build-id ${{ github.run_id }} --group "Shard $SHARD" --spec "cypress/e2e/shard-${SHARD}/*.cy.js"  # Use environment variable $SHARD

      - name: Upload Cypress Test Results (Optional)
        if: always()
        uses: actions/upload-artifact@latest
        with:
          name: cypress-test-results
          path: cypress/videos  # Adjust the path as needed
