name: Cypress Tests

on:
  push:
    branches:
      - main  # Trigger CI on push to the main branch (or any other branches you choose)
  pull_request:
    branches:
      - main  # Trigger CI on pull requests to the main branch

jobs:
  cypress-tests:
    runs-on: ubuntu-latest  # You can also use macos-latest or windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checks out the repository

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Specify the Node.js version (adjust as needed)

      - name: Install dependencies
        run: npm install  # Install dependencies using npm ci for a clean install

      - name: Run Cypress Tests
        run: npx cypress run  # Runs Cypress tests in headless mode

      - name: Upload Cypress Test Results (Optional)
        if: always()  # This ensures the upload step runs even if tests fail
        uses: actions/upload-artifact@v3
        with:
          name: cypress-test-results
          path: cypress/videos  # Upload videos of Cypress tests
